language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

addons:
  apt:
    packages:
    - oracle-java8-installer # Updates JDK 8 to the latest available.
    - oracle-java9-installer # Updates JDK 9 to the latest available.

cache:
  directories:
  - $HOME/.m2
